# .github/workflows/main.yaml

name: Daily Node.js Cron Job

# Controls when the workflow will run
on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '45 0 * * *'

  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-node-app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # specify the Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the Node.js application
      - name: Run application
        run: node index.js  # specify the path to your main file

      # Optional: Step 5: Send success/failure notifications
      - name: Send notification on failure
        if: failure()
        run: echo "The cron job failed."  # Replace with your notification command
